name: Weekly Build and Update Latest Release

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC. Change as needed (e.g., '0 0 * * 0' for Sunday).
  workflow_dispatch:  # Optional: allows manual triggering from the GitHub UI
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ipinfo
        run: |
          go install .

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: 'disposable/cloud-ip-ranges'
          path: cloud-ip-ranges

      - name: Build cloud
        run: |
          ipinfo -disp-cloud-dir cloud-ip-ranges -output cloud.bin

      - name: Upload cloud.bin
        if: hashFiles('cloud.bin') != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/vearutop/ipinfo/releases/272330670/assets{?name,label}"
          asset_path: ./cloud.bin
          asset_name: cloud.bin
          asset_content_type: application/octet-stream

      - name: Build ASN lite
        run: |
          wget https://git.io/GeoLite2-ASN.mmdb
          ipinfo -mmdb GeoLite2-ASN.mmdb -mmdb-type asn -output asn-lite.bin

      - name: Upload asn-lite.bin
        if: hashFiles('asn-lite.bin') != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/vearutop/ipinfo/releases/272330670/assets{?name,label}"
          asset_path: ./asn-lite.bin
          asset_name: asn-lite.bin
          asset_content_type: application/octet-stream

      - name: Build City lite
        run: |
          wget https://git.io/GeoLite2-City.mmdb
          ipinfo -mmdb GeoLite2-City.mmdb -mmdb-type city -output city-lite.bin

      - name: Upload city-lite.bin
        if: hashFiles('city-lite.bin') != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/vearutop/ipinfo/releases/272330670/assets{?name,label}"
          asset_path: ./city-lite.bin
          asset_name: city-lite.bin
          asset_content_type: application/octet-stream

      - name: Build Country lite
        run: |
          wget https://git.io/GeoLite2-Country.mmdb
          ipinfo -mmdb GeoLite2-Country.mmdb -mmdb-type country -output country-lite.bin

      - name: Upload country-lite.bin
        if: hashFiles('country-lite.bin') != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/vearutop/ipinfo/releases/272330670/assets{?name,label}"
          asset_path: ./country-lite.bin
          asset_name: country-lite.bin
          asset_content_type: application/octet-stream
